# Generated by Django 5.1.6 on 2025-02-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['data']},
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Imagem do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(default='', related_name='products', to='main.categoria'),
        ),
    ]
